/* eslint-disable */
// AUTO-GENERATED by scripts/sync-tileset-assets-from-maps.mjs — do not edit.
// Source: tilesets[] on maps in public/assets/maps/registry.json
import type { TilesetEntry } from './mapRegistry'

export const TILESET_ASSETS: TilesetEntry[] = [
  {
    name: "tileset5_export",
    key: "ts_tileset5_export",
    url: "/assets/maps/tilesets/tileset5_export.png",
  },
  {
    name: "tileset6_export",
    key: "ts_tileset6_export",
    url: "/assets/maps/tilesets/tileset6_export.png",
  },
  {
    name: "tileset1",
    key: "ts_tileset1",
    url: "/assets/maps/tilesets/tileset1.png",
  },
  {
    name: "tileset1-repositioning",
    key: "ts_tileset1-repositioning",
    url: "/assets/maps/tilesets/tileset1-repositioning.png",
  },
  {
    name: "Special_Zones",
    key: "ts_Special_Zones",
    url: "/assets/maps/tilesets/Special_Zones.png",
  },
  {
    name: "fountain-sculptures",
    key: "ts_village_fountain-sculptures",
    url: "/assets/maps/tilesets/village/fountain-sculptures.png",
  },
  {
    name: "decor-rugs-1",
    key: "ts_village_decor-rugs-1",
    url: "/assets/maps/tilesets/village/decor-rugs-1.png",
  },
  {
    name: "office-anim",
    key: "ts_office-anim",
    url: "/assets/maps/tilesets/office-anim.png",
  },
  {
    name: "world-stub",
    key: "ts_world-stub",
    url: "/assets/maps/tilesets/world-stub.png",
  },
]
